import { AppSidebar } from "@/components/Dashboard/AppSidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { Metadata } from "next";
import { cookies } from "next/headers";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Meevent - Dashboard",
    description: "Generated by create next app",
}

export default async function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {

    const cookieStore = await cookies();
    const themeCookie = cookieStore.get("theme")?.value;
    const raw = cookieStore.get("userData")?.value;
    const userData = raw ? JSON.parse(raw) : null;

    return (
        <SidebarProvider>
            <AppSidebar userData={userData} themeCookie={themeCookie ? themeCookie : ""} />
            <main className="flex-1">
                {children}
            </main>
            <Toaster />
        </SidebarProvider>
    )
}