import { AppSidebar } from "@/components/Dashboard/AppSidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { Metadata } from "next";
import { Toaster } from "sonner";

export const metadata: Metadata = {
    title: "Meevent - Dashboard",
    description: "Generated by create next app",
}

export default function DashboardLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <SidebarProvider>
            <AppSidebar />
            <main className="flex-1">
                {children}
            </main>
            <Toaster />
        </SidebarProvider>
    )
}